name: fl_financial
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  get: ^3.4.0
  percent_indicator: "^2.1.5"
  intl: ^0.16.1
  http: ^0.12.2
  flutter_material_color_picker: ^1.0.5
  shared_preferences: ^0.5.8
  flutter_launcher_icons: ^0.7.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/piggybank.png"

flutter:
  uses-material-design: true

  assets:
    - assets/finances.jpg
    - assets/piggybank_outline.png
    - assets/piggybank.png
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700